name: Latest book list from a goodreads
on:
  schedule: # Run workflow automatically
    # This will make it run at 1:00 AM UTC every 3 days
    - cron: "0 1 1/3 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what you're currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: zwacky/goodreads-profile-workflow@main
        with:
          # Replace this with your goodreads user id
          goodreads_user_id: "185356984-gabriele"
          shelf: "reading_public"
          template: "- $title by $author ($published_year)"
